### ISSUE TITLE
Enable CONFIG_BCM2835_DEVGPIOMEM in config?

### ISSUE THREAD

**Issue by ava1ar** [sakaki-/bcmrpi3-kernel#1]
Hi!

Thanks for the kernel builds! I am using them with my ArchLinux ARM and wanted to use GPIO functionality, but can't do it without root. This is because CONFIG_BCM2835_DEVGPIOMEM config option is not set. Can you set it to the y or m please - it won't hurt anybody, but will make possible to use your kernel with GPIO devices. If not, I will need to build my own kernel :(

**Comment by sakaki-** [comment]
Is this on in the Raspbian 32-bit kernel?

In any event, I don't have a problem adding it in the short term, but it might be an idea to open an issue with [upstream](https://github.com/raspberrypi/linux) to have this added to the 64-bit `bcmrpi3_defconfig`?

**Comment by ava1ar** [comment]
Yes, it is on on 32-bit kernel. I already submitted request upstream: https://github.com/raspberrypi/linux/issues/2514
Hope they will enable it, unless this is really good reason not to. If you can include it to your kernel right now it would be cool, but I understand if you don't want, since your are trying to build the original config with minimal changes. 
Thanks for your work anyway!

**Comment by sakaki-** [comment]
Well that was quick: your request raspberrypi/linux#2514 just got [committed](https://github.com/raspberrypi/linux/commit/b6a574b3e3170b4dd2f297ba7f4dbc36f759983a).
I triggered a manual run of the kernel build process to pick this up, creating release [4.14.34.20180417](https://github.com/sakaki-/bcmrpi3-kernel/releases/tag/4.14.34.20180417), which has `CONFIG_BCM2835_DEVGPIOMEM` set, mirroring the upstream config change ^-^

Please let me know if you have any trouble with it (or subsequent weekly builds).

Best, sakaki

**Comment by ava1ar** [comment]
Thanks, sakaki. Tested your new kernel build already and confirm it is working fine! Closed upstream issue and closing this one as well. Thanks a lot for your attention and your help! Have a great day!

**Comment by sakaki-** [comment]
@ava1ar,

FYI, as of the latest (4.14.98.20190213) release, the release tarball also includes:
* `/boot/overlays/README`, `/boot/overlays/*.dtbo` (device tree overlays)
* `/boot/bcm2710-rpi-cm3.dtb` (additional DTB for the compute module 3)

Just letting you know, in case any of that would require changes to your AUR package.

Best, sakaki
