### ISSUE TITLE
Requesting CONFIG_DM_CACHE=m and CONFIG_DM_CACHE_SMQ=m

### ISSUE THREAD

**Issue by ShapeShifter499** [sakaki-/bcmrpi3-kernel#2]
I'm requesting these two modules because they are required for the 'sd-lvm2' and 'lvm2' mkinitcpio modules.   Can you please add these to the kernel config and compile?

I'm trying to set up a full disk encryption on my Raspberry Pi 3B+ and I need these modules so I can setup a ssh init and decrypt remotely.   This kernel is picked up by the AUR package here https://aur.archlinux.org/packages/linux-aarch64-raspberrypi-bin/

**Comment by sakaki-** [comment]
Hi,

I'm going to set up an additional `bcmrpi3-kernel-bis` weekly autobuild shortly, using an augmented config (including the various additional settings people have requested) and will activate your requested changes there.

That way, this project can continue to host a 'pure' (wrt upstream) build (usable for testing etc.)

Should be up in the next week or so.

Best, sakaki

On 8 May 2018 01:19:34 GMT-04:00, Lance <notifications@github.com> wrote:
>I'm requesting these two modules because they are required for the
>'sd-lvm2' and 'lvm2' mkinitcpio modules.    
>
>I'm trying to set up a full disk encryption on my Raspberry Pi 3B+ and
>I need these modules so I can setup a ssh init and decrypt remotely.  
>This kernel is picked up by the AUR package here
>https://aur.archlinux.org/packages/linux-aarch64-raspberrypi-bin/
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/sakaki-/bcmrpi3-kernel/issues/2

-- 
sakaki@deciban.com

**Comment by ava1ar** [comment]
@ShapeShifter499,
Are this modules enabled in upstream kernel for RaspberryPi (armhf one)? If yes, you can request also enabling them for the aarch64 config.

**Comment by ShapeShifter499** [comment]
@ava1ar one of them is on the arm7 configuration from what I can tell.    I've made a request anyways.

**Comment by ShapeShifter499** [comment]
@sakaki- @ava1ar My request has been merged into the latest kernel.   https://github.com/raspberrypi/linux/issues/2553#issuecomment-388652830

**Comment by ShapeShifter499** [comment]
https://github.com/raspberrypi/linux/commit/2a6adf636ba83c450f0140b2dbcda5fc66e6b0de

**Comment by sakaki-** [comment]
Closing, as the regular weekly autobuild has just picked up the new upstream config today, so the latest `bcmrpi3-defconfig` release ([4.14.39.20180514](https://github.com/sakaki-/bcmrpi3-kernel/releases/tag/4.14.39.20180514)) has your [desired changes applied](https://github.com/sakaki-/bcmrpi3-kernel/blob/4360ea09213511d3a054ed749d301d50406ce49b/config#L1700-L1701) ^-^

Still going to roll out a -bis variant shortly though, as there are a number of other config entries (not in armhf) that'd be nice to have bundled.
