### ISSUE TITLE
Reuesting AppArmor settings to be compiled.

### ISSUE THREAD

**Issue by ShapeShifter499** [sakaki-/bcmrpi3-kernel#3]
Last time you said you were planning on adding a -bis build including some extra options that would be useful. Can I ask that AppArmor be added to the regular build or the -bis build?  This would be for security purposes.

CONFIG_SECURITY_APPARMOR=y
CONFIG_SECURITY_APPARMOR_BOOTPARAM_VALUE=1
CONFIG_DEFAULT_SECURITY_APPARMOR=y
CONFIG_AUDIT=y

**Comment by sakaki-** [comment]
I have the bis build in testing now as a private repo. When I move it public I'll add those settings.

**Comment by ava1ar** [comment]
@ShapeShifter499,
@sakaki- just released new kernel project, which will accept the PR with custom kernel configurations (https://github.com/sakaki-/bcmrpi3-kernel-bis). So, prepare a PR with desired changes to the mentioned project for review.

**Comment by sakaki-** [comment]
@ShapeShifter499, @ava1ar has it exactly right. Please submit a PR on [bcmrpi3-kernel-bis](https://github.com/sakaki-/bcmrpi3-kernel-bis) with these changes. You need to target the end of the [conform_config.sh](https://github.com/sakaki-/bcmrpi3-kernel-bis/blob/master/conform_config.sh) script.

Going forward the -bis variant will be autobuilt and released in lockstep with this project's releases (first run of the modified build script just went through, as it happens), so if I merge your PR you'll only have at most a week to wait for a first usable build.

Incidentally, the -bis variant will be the default kernel used by my [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit) image as of the (forthcoming) 1.2.2 release (although users will still have the option of switching back to the default kernel (i.e., the one from this project) if they wish).

**Comment by ShapeShifter499** [comment]
I'll close this then.

I'll make the PR if no one else does.  But I first have to sort out issues with why my Pi,  at this point I'm not even sure if I'll keep my Pi if the issues cannot be fixed.
