### ISSUE TITLE
Where do I find the kernel headers for this build?

### ISSUE THREAD

**Issue by ShapeShifter499** [sakaki-/bcmrpi3-kernel#4]
I was looking into building "cryptodev-linux" but that requires kernel headers, where would I find them for this particular build?

**Comment by sakaki-** [comment]
If you are running Gentoo, `emerge` `>=sys-kernel/linux-headers-4.14` (it is fine to use headers newer than your kernel, see [these notes](https://wiki.gentoo.org/wiki/Linux-headers)). For example, my [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit) image (which uses kernels from this project) ships with [`sys-kernel/linux-headers-4.15`](https://github.com/sakaki-/gentoo-on-rpi3-64bit/blob/master/reference/world-all-packages#L652).

Other distros will have their own equivalent packages.

**Comment by ShapeShifter499** [comment]
Interesting, I know the distro I use Arch Linux ARM has the Aarch64 headers but they are for kernel 4.16     It's good to know I can use those.

**Comment by ShapeShifter499** [comment]
I suppose I'll close this issue, thank you for the help.
