### ISSUE TITLE
kernel BUG at arch/arm64/kernel/fpsimd.c:282!   AND other issues

### ISSUE THREAD

**Issue by ShapeShifter499** [sakaki-/bcmrpi3-kernel#5]
I'm making use of this kernel on Arch Linux ARM with the AUR package https://aur.archlinux.org/packages/linux-aarch64-raspberrypi-bin/    I've been seeing some strange messages in my dmesg output and I'm worried it could lead to data corruption.  Does anyone know what it is and how it could be fixed if it's serious? 

These messages appear when there is high I/O.  Such as when I'm attempting to move data from one USB hard drive to another. 

All of my devices are encrypted including the rootfs.  I'm able to remotely decrypt it using a initram hook and dropbear ssh. 

Following snippets of logs where the messages show.
https://gist.github.com/ShapeShifter499/df184265fbf0672140d396d89510d184
https://gist.github.com/ShapeShifter499/3af51b6c3d87c07e300110f81e162df8
https://gist.github.com/ShapeShifter499/8c43fca9b6404126c6971564d695be4b

**Comment by ShapeShifter499** [comment]
@ava1ar  I'm mentioning you in case you might be able to help out here.

**Comment by ava1ar** [comment]
@ShapeShifter499 
This project is just a build for official config for RPi kernel (https://github.com/raspberrypi/linux), you should submit the bug there, not here. Kernel issues support is outside the scope of this project.
However, aarch64 is not officially supported for RaspberryPi, so there is no guarantee, someone will pay attention to the issue (only if you can replicate your setup with official armhf kernel build and reproduce issue there). 
Also, I personally think that RaspberryPi is a proper hardware for moving large amount of data via USB bus.

**Comment by ShapeShifter499** [comment]
I've gone ahead and opened a issue ticket on their github, https://github.com/raspberrypi/linux/issues/2575

**Comment by ShapeShifter499** [comment]
@sakaki- would you be willing to build a test kernel that would include the below workarounds?  The suggestion from my issue ticket over at Raspberry Pi.


> Looks like some issue with using neon in 64-bit kernel.
...
arch/arm64/kernel/fpsimd.c, 282 BUG_ON(!may_use_simd());
...
Try disabling NEON accelerated AES, CRYPTO_AES_ARM64_BS (and ? CRYPTO_AES_ARM64_NEON_BLK) (or even all of ARM64_CRYPTO) as a workaround.
>

**Comment by sakaki-** [comment]
Happy to do so, but it will be a week or so before I get the chance, as travelling atm. Best, sakaki 

On 13 June 2018 13:35:24 CEST, Lance <notifications@github.com> wrote:
>@sakaki- would you be willing to build a test kernel that would include
>the below workarounds?  The suggestion from my issue ticket over at
>Raspberry Pi.
>
>
>> Looks like some issue with using neon in 64-bit kernel.
>...
>arch/arm64/kernel/fpsimd.c, 282 BUG_ON(!may_use_simd());
>...
>Try disabling NEON accelerated AES, CRYPTO_AES_ARM64_BS (and ?
>CRYPTO_AES_ARM64_NEON_BLK) (or even all of ARM64_CRYPTO) as a
>workaround.
>>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sakaki-/bcmrpi3-kernel/issues/5#issuecomment-396906552

-- 
sakaki@deciban.com

**Comment by ShapeShifter499** [comment]
That's fine. Thank you for taking the time to get these kernels built.

**Comment by sakaki-** [comment]
@ShapeShifter499 - please try the following kernel / module set. It has `ARM64_CRYPTO` disabled, but is otherwise the same as the most recent `-bis` kernel.
[test-kernel.tar.zip](https://github.com/sakaki-/bcmrpi3-kernel/files/2131017/test-kernel.tar.zip)

**Comment by ShapeShifter499** [comment]
I'm closing this since I no longer use the Raspberry Pi 3B+ for the original purpose that required a 64 bit kernel.

I have since moved all services to a "Up Board" which is a x86_64 bit SBC with an x5-Z8350 Intel processor with 4GB of RAM.
