### ISSUE TITLE
Requesting CONFIG_CGROUP_NET_PRIO=y

### ISSUE THREAD

**Issue by sanpoChew** [sakaki-/bcmrpi3-kernel#6]
There seems to be an issue with docker and systemd 240 that is resolved by enabling this flag:

https://github.com/docker/for-linux/issues/545

**Comment by sakaki-** [comment]
Hi @sanpoChew,

this project (bcmrpi3-kernel) is a vanilla build of the upstream`bcmrpi3_defconfig`, so you need to submit requests for changes to the config there.

However, I also maintain a parallel kernel autobuild, [bcmrpi3-kernel-bis](https://github.com/sakaki-/bcmrpi3-kernel-bis) into which changes to the config _are_ accepted (please see the README there for details; incidentally this -bis kernel is the one used by my [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit) project). If you submit this change as a PR there I will merge it. Thanks!

**Comment by sanpoChew** [comment]
Hi @sakaki- 

Thanks for the quick reply, I've submitted an issue to https://github.com/raspberrypi/linux for now. Definitely piqued my interest with https://github.com/sakaki-/gentoo-on-rpi3-64bit though, might head down that rabbit hole at some point!
