### ISSUE TITLE
Preparations for 4.19.y?

### ISSUE THREAD

**Issue by eccgecko** [sakaki-/bcmrpi3-kernel#7]
Hi Sakaki. Firstly, thanks for this project. It's really great, and I have been using it on my arch sytem using the AUR package https://aur.archlinux.org/packages/linux-aarch64-raspberrypi-bin/

I was just wondering if you had done any preparation for the imminent migration by the Pi people to the 4.19.y branch of the linux kernel for the standard stable branch? According to their forums and a few posts in their GitHub issues, the switch is looking likely to occur in the next month or two. The problem is, I believe the switch could cause issues for 64-bit kernels on the Pi. I have been building and testing the standard 64-bit `bcmrpi3_defconfig` from the rpi-4.19.y branch, and I have had a lot of issues with not being able to reboot, and sometimes not being able to boot at all, with lots of kernel panics etc. Have you done any testing of the 4.19.y branch and experienced any issues? Will you hold this package on 4.14.y when Rpi switch, or will it automatically switch to 4.19.y once they make that the stable branch?

**Comment by sakaki-** [comment]
Hi @eccgecko, glad you are finding the autobuild useful ^-^

To your questions: yes, I currently have another, private-repo autobuild tracking `rpi-4.19.y`, and it does still have some issues (I've avoided rolling it out as the default kernel for the next release of [gentoo-on-rpi3-64bit](https://github.com/sakaki-/gentoo-on-rpi3-64bit), for example; sticking with 4.14.y for now). The way things are set up for _this_ project, it will automatically switch over to building 4.19.y once the default branch is changed. I could force it to stay with 4.14.y, but I'm more likely to create a separate (public) legacy autobuild project (if necessary) for that.

In the meantime, I think it'd be useful for you to report issues with 4.19.y (if you aren't already doing so) on [this thread](https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=232684) on the rpi forums (you may at least want to +1 the issues reported in [this post](https://www.raspberrypi.org/forums/viewtopic.php?p=1432356#p1432356), which seem similar to the ones you are reporting - assuming you aren't "jimbojones" of course ^-^). The best thing would be to avoid RPF cutting over until these issues are ironed out.

Best, sakaki

**Comment by sakaki-** [comment]
Oops, looks like 4.19.y [just became the default branch](https://forums.gentoo.org/viewtopic-p-8311724.html#8311724)...

**Comment by sakaki-** [comment]
Release 1.4.0 of the image is now out, featuring a 4.19 kernel. The reboot behaviour seemed to have materially improved in the latest revisions, so in the end I decided to go with it. And on the upside, you do get access to the camera module and hardware video codecs  ^-^

**Comment by sakaki-** [comment]
Closing now, as 4.19 is relatively well established.
