### ISSUE TITLE
RPi4 support?

### ISSUE THREAD

**Issue by ava1ar** [sakaki-/bcmrpi3-kernel#8]
Hi!

What is the plan for RPi4 support? Will you have separate build with PR4-optimized kernel or just support it in this one?

**Comment by sakaki-** [comment]
It will be a separate build (relying on a different config) I would imagine. Just got my RPi4s today, so will be a while before I have anything ready to show on that front.

**Comment by sakaki-** [comment]
Hi @ava1ar 

still a bit early for an autobuild yet (given current issues with the 64-bit `bcm2711_defconfig` kernel), but if you want to try out an early 64-bit arch boot on a Pi4, I have created a mini-tarball will all the necessary files (similar to that provided by this project's releases, but with a self-sufficient bootfs).

For details, please see [here](https://www.raspberrypi.org/forums/viewtopic.php?p=1492322#p1492322).

hth, sakaki

**Comment by sakaki-** [comment]
Hi @ava1ar,

So, I've started a preliminary pair (vanilla and "-bis") of kernel autobuilds for `bcm2711_defconfig` now. You can find the projects [here](https://github.com/sakaki-/bcm2711-kernel) and [here](https://github.com/sakaki-/bcm2711-kernel-bis) respectively.

This is not yet production ready, so please let me know of any issues you encounter!

Best, sakaki

**Comment by sakaki-** [comment]
@ava1ar - going to close this now - the two `bcm2711_defconfig` autobuilds ([here](https://github.com/sakaki-/bcm2711-kernel) and [here](https://github.com/sakaki-/bcm2711-kernel-bis)) are now good for production use. Please let me know if there are any problems.

Best, sakaki
